### ISSUE TITLE
DC Configuration script runs with errors

### ISSUE THREAD

**Issue by aalborz** [blackhillsinfosec/EventLogging#10]
Tried running the DC Configurator - No Audit on DC. No GPOs are created and I'm getting errors (see attached).

!
![DC_Config_Errors](https://user-images.githubusercontent.com/9065072/175395392-5368c389-fd5a-409b-94fe-532aa81f6e10.JPG)

**Comment by mon0pixel** [comment]
I will look into the path errors. The output says your gpo was created and is in the gpo objects folder. You will need to link it manually.

**Comment by mon0pixel** [comment]
I am not able to replicate this issue. 
The GPO has been created in this example and is stored in your GPO Objects folder. You will need to like it to the OUs you want it in manually. 
The $MyInvocation variable is populated at runtime. If it is null then that usually means its and ISE or Powershell window. You might try running `powershell.exe /c ./DC-Configurator-NoAudit.ps1` and see if you still get the error. In this case the errors should not effect the integrity of the code as it is only being used to set the location back to where it started.
