### ISSUE TITLE
$MyInvocation.MyCommand.Path value is null

### ISSUE THREAD

**Issue by mon0pixel** [blackhillsinfosec/EventLogging#12]
![image](https://user-images.githubusercontent.com/36604349/179759002-6d81290c-2cf3-40ab-a9f2-ac07bf9d2a6f.png)

I was trying to be clever here and it back fired. These errors dont break the script but it does cause some evil red text that needs to be dealt with.

**Comment by Kadawi** [comment]
Submitted fix in pull request #14

**Comment by mon0pixel** [comment]
Fixed in #14
