### ISSUE TITLE
System.Windows.Forms not present on Windows Server Core

### ISSUE THREAD

**Issue by nolsen311** [blackhillsinfosec/EventLogging#18]
function get-csvfilepath loads an assembly that is not present on Server Core and will fail.

I committed a change to wrap this in try-catch and use read-host if the load fails (I think), but have no idea how to move this forward...or even if my rough "fix" works properly.

**Comment by mon0pixel** [comment]
I dont see the code you pushed. I would recommend forking the repo and then changing the code there then make a pull request back to the project.

**Comment by mon0pixel** [comment]
Fixed by #19
