### ISSUE TITLE
HKCU Entries

### ISSUE THREAD

**Issue by kevinelwell** [blackhillsinfosec/EventLogging#6]
Your .XML files contain HKCU registry entries. Since the Sysmon service runs under the SYSTEM account, Sysmon would be looking for any HKCU registry items under the SYSTEM account; NOT the logged-on user(s). Several of your .XML files contain HKCU registry entries. Since the Sysmon service runs under the SYSTEM account, Sysmon would be looking for any HKCU registry items under the SYSTEM account; NOT the logged-on user(s).

Reference: https://github.com/olafhartong/sysmon-modular/issues/130

**Comment by icass** [comment]
Awesome teamwork! ❣️🔥📡📞📡🎯🍎🍎♠️♠️🪙🥓

**Comment by mon0pixel** [comment]
We will be pointed this repo to in some upcoming releases as the group over their is able to dedicate more time to maintaining the config than we are at this time.
