### ISSUE TITLE
Sequence of PS scripts execution & Location of certificate

### ISSUE THREAD

**Issue by aalborz** [blackhillsinfosec/EventLogging#8]
Couple of silly questions:
1- What is the sequence of executing the scripts in each DefCon?
2- Where do I get the certificate - ca.crt (used in DefCon4)?

**Comment by mon0pixel** [comment]
You can execute the dc and wec scripts in whichever order you wish. There is not requirement to run one before the other. The ca is something you will create if you are using logstash as part of an ELK stack. It is not required if you only want to setup forwarding to the WEC.
